server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: zc_code@163.com
    password: ZhangCheng1995

  #这里省略MySQL配置信息
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
    #这里省略MySQL配置信息
    #这里省略Redis配置信息
    data:
      mongodb:
        host: localhost
        port: 27017
        database: emos
        authentication-database: admin
        username: admin
        password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire:  5
    #令牌缓存时间（天数）
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.99.101/create_face_model
    checkinUrl: http://192.168.99.101/checkin
  email:
    system: zc_code1@163.com
    hr: 1272189720@qq.com
  image-folder: D:/emos/image
  code: HelloWorld
  recieveNotify: http://PC电脑的IP地址:8080/emos-wx-api/meeting/recieveNotify

wx:
  app-id: wx856314c4957f20b4
  app-secret: a03fb79ddd70726262bbf60bdbcc819f

workflow:
  url:  http://CentOS的IP地址:9090/emos-workflow

trtc:
  appid: 1400499184 #TRTC的APPID
  key: 491ff426170917058728ff4b29e42305dd3ffad86c6c79cf42efd4fe18f2c927 #TRTC的密钥
  # 一天
  expire: 86400
